### ISSUE TITLE
Image is not building

### ISSUE THREAD

**Issue by blacksailer** [FAU-DLM/GPU-Jupyterhub#1]
Hello!
When trying to build base-notebook-gpu docker throws ```fix-permissions: Access denied``` in [this line](https://github.com/FAU-DLM/GPU-Jupyterhub/blob/master/Jupyter_Image/base-notebook/Dockerfile#L49). I fix this by replacing [this file](https://github.com/FAU-DLM/GPU-Jupyterhub/blob/abc684cac733e704b96fdc87eac4fc87a5f935e0/Jupyter_Image/base-notebook/fix-permissions)
 to [that file](https://github.com/jupyter/docker-stacks/blob/master/base-notebook/fix-permissions) .

Thought that you should know

**Comment by yusuke0324** [comment]
Hi, @blacksailer 
The two files looks same to me... could you explain a bit more?  I got the permission error when 
`$docker build -t base-notebook-gpu .`

the error is
~~~
Step 11/26 : RUN useradd -m -s /bin/bash -N -u $NB_UID $NB_USER &&     mkdir -p $CONDA_DIR &&     chown $NB_USER:$NB_GID $CONDA_DIR &&     fix-permissions $HOME &&     fix-permissions $CONDA_DIR
 ---> Running in bed04ab60675
/bin/sh: 1: fix-permissions: Permission denied
~~~

**Comment by Rachidramadan1990** [comment]
Hello, 
did you solve the problem? If yes, how?

**Comment by SamirJabari** [comment]
I can't reproduce this issue... it simply works for me... I will have a more in depth look into what may be the problem... sorry

**Comment by SamirJabari** [comment]
Ok i resolved the issue change the file permissions of fix-permissions with "chmod o=rx" fix-permissions inside the base-notebook-gpu folder and the tensorflow-notebook-gpu folder... then if you build the image the error is gone
