### ISSUE TITLE
Miniconda version is changed

### ISSUE THREAD

**Issue by blacksailer** [FAU-DLM/GPU-Jupyterhub#2]
Miniconda version changed, md5sum not valid.
https://github.com/FAU-DLM/GPU-Jupyterhub/blob/55123091dadebf752b0193ceba0fd44a42247085/Jupyter_Image/base-notebook/Dockerfile#L62

**Comment by Rachidramadan1990** [comment]
How to solve this problem?

**Comment by SamirJabari** [comment]
Ok I should fix that to be more generic... for now:
At https://repo.continuum.io/miniconda/ loook for
Miniconda3-latest-Linux-x86_64.sh and the appropriate checksum right now it is 
a946ea1d0c4a642ddf0c3a26a18bb16d
in line 65 replace the checksum with after echo with the above checksum:
so replace this:    
echo "**7fe70b214bee1143e3e3f0467b71453c** *Miniconda3-${MINICONDA_VERSION}-Linux-x86_64.sh" | md5sum -c - && \

with that:     
echo "**a946ea1d0c4a642ddf0c3a26a18bb16d** *Miniconda3-${MINICONDA_VERSION}-Linux-x86_64.sh" | md5sum -c - && \

Hope that solves this for now...
