### ISSUE TITLE
PostgresPassword and Configproxy_auth_token

### ISSUE THREAD

**Issue by Rachidramadan1990** [FAU-DLM/GPU-Jupyterhub#3]
How do I get PostgresPassword and Configproxy_auth_token?
best!

**Comment by SamirJabari** [comment]
Hi, it should work by defining those variables in the. env file.
This may not be the best method in terms of security but works just fine.
Or generate a token on the command line like this
export CONFIGPROXY_AUTH_TOKEN='openssl rand -hex 32'
Hope that helps
