### ISSUE TITLE
tornado.httpclient.HTTPClientError: HTTP 403: Forbidden

### ISSUE THREAD

**Issue by udaynaik** [FAU-DLM/GPU-Jupyterhub#4]
I build the image but have run into this issue. I have been trying get this to work but no matter with SSL/no SSL/different ports/checking for a running configureable proxy etc has not helped. Hoping you might throw some light on this issue with this.

jupyterhub | [I 2018-09-21 16:45:06.198 JupyterHub app:1667] Using Authenticator: jupyterhub.auth.PAMAuthenticator-0.9.3
jupyterhub | [I 2018-09-21 16:45:06.198 JupyterHub app:1667] Using Spawner: dockerspawner.dockerspawner.DockerSpawner-0.9.1
jupyterhub | [I 2018-09-21 16:45:06.204 JupyterHub app:1053] Writing cookie_secret to /data/jupyterhub_cookie_secret
jupyterhub | [I 2018-09-21 16:45:06.236 alembic.runtime.migration migration:117] Context impl SQLiteImpl.
jupyterhub | [I 2018-09-21 16:45:06.237 alembic.runtime.migration migration:122] Will assume non-transactional DDL.
jupyterhub | [I 2018-09-21 16:45:06.258 alembic.runtime.migration migration:327] Running stamp_revision  -> 896818069c98
jupyterhub | [I 2018-09-21 16:45:06.575 JupyterHub auth:547] Creating user: adduser -q --gecos '""' --disabled-password admin
jupyterhub | [I 2018-09-21 16:45:06.700 JupyterHub auth:547] Creating user: adduser -q --gecos '""' --disabled-password user
jupyterhub | [I 2018-09-21 16:45:06.817 JupyterHub app:1849] Hub API listening on http://jupyterhub:5264/hub/
jupyterhub | [I 2018-09-21 16:45:06.818 JupyterHub proxy:567] Starting proxy @ http://:443/
jupyterhub | 16:45:07.228 - info: [ConfigProxy] Proxying https://*:443 to (no default)
jupyterhub | 16:45:07.229 - info: [ConfigProxy] Proxy API at http://127.0.0.1:8001/api/routes
jupyterhub | 16:45:07.371 - warn: [ConfigProxy] 403 GET /api/routes 
jupyterhub | [E 2018-09-21 16:45:07.371 JupyterHub app:1952]
jupyterhub |     Traceback (most recent call last):
jupyterhub |       File "/opt/conda/lib/python3.6/site-packages/jupyterhub/app.py", line 1950, in launch_instance_async
jupyterhub |         await self.start()
jupyterhub |       File "/opt/conda/lib/python3.6/site-packages/jupyterhub/app.py", line 1895, in start
jupyterhub |         await self.proxy.check_routes(self.users, self._service_map)
jupyterhub |       File "/opt/conda/lib/python3.6/site-packages/jupyterhub/proxy.py", line 57, in locked_method
jupyterhub |         return await method(*args, **kwargs)
jupyterhub |       File "/opt/conda/lib/python3.6/site-packages/jupyterhub/proxy.py", line 297, in check_routes
jupyterhub |         routes = await self.get_all_routes()
jupyterhub |       File "/opt/conda/lib/python3.6/site-packages/jupyterhub/proxy.py", line 733, in get_all_routes
jupyterhub |         resp = await self.api_request('', client=client)
jupyterhub |       File "/opt/conda/lib/python3.6/site-packages/jupyterhub/proxy.py", line 694, in api_request
jupyterhub |         result = await client.fetch(req)
jupyterhub |     tornado.httpclient.HTTPClientError: HTTP 403: Forbidden

**Comment by SamirJabari** [comment]
I personally have no idea about the issue, but i found this issue might be a duplicate or related to this issue on the jupyterhub project itself... maybe you check this out...
#https://github.com/jupyterhub/jupyterhub/issues/1377 #

**Comment by whlteXbread** [comment]
Quick note---if you don't remove comments in the `.env` file you'll have some trouble. See [this comment](https://github.com/jupyterhub/jupyterhub/issues/2173#issuecomment-435721060).
